### PR TITLE
Add copy robot API key to clipboard

### PR DESCRIPTION
**Pull request by SashaBajzek**
The reusable Input component is a functional component, so according to React docs, a forwarding ref is needed (https://reactjs.org/docs/forwarding-refs.html).

I only have the 'copy API key to clipboard' show up when the API key is toggled to 'Show API key'.  Then the type isn’t set to password, so it is copiable.

I have Prettier on, so it might have formatted some indentions differently.  If it bothers you, let me know and I can make the pull request again with Prettier turned off. :)

### CODE REVIEW

**Comment by jillytot** [comment]
Pulled and tested. 
The copy / paste works great, is there a way to allow copy and pasting to happen while the key is hidden? I'd like to be able to copy to clipboard whether it's revealed or not. Looking good so far!

**Comment by SashaBajzek** [comment]
I followed this example to get the copy to work when the password is hidden:
https://stackoverflow.com/questions/17527870/how-does-trello-access-the-users-clipboard

I add a textarea with the password to the DOM that is hidden by CSS & use that for the copy to clipboard.

I tested on Chrome & Firefox which works.  But in Safari, the copy does NOT work.  I'm going to explore more to see how to get Safari to work

**Comment by SashaBajzek** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
Would work for Safari, but it requires https

**Comment by SashaBajzek** [comment]
Okay, I think it works for Chrome, Firefox, and Safari now.  Please give it a try and let me know what you think  :)

**Comment by jillytot** [comment]
Omg this is really nice! Thanks so much Sasha. I'm gonna merge it.

**Pull request merged**
