### PR TITLE
quick and dirty censor function

### PR DESCRIPTION
**Pull request by bmorrison4**
right now only looks for explicit matches against a list and substitutes them with an "appropriate" replacement.

### CODE REVIEW

**Comment by bmorrison4** [comment]
No longer quick and dirty. Implemented metaphone phonetic filtering.

**Comment by jillytot** [comment]
I still need this module to take in an array of bad word variations that will equal a replacement word.

**Comment by bmorrison4** [comment]
I believe this should do that now.

**Comment by bmorrison4** [comment]
Closed because I had to reclone the repo so I don't think this works anymore. New PR at #79

**Pull request closed without merging**
